# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind / split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %

# Move current window left/right and follow it
# Linux Configuration
bind-key -n C-S-Left swap-window -t -1 \; select-window -t -1
bind-key -n C-S-Right swap-window -t +1 \; select-window -t +1
# Windows Configuration
bind-key , swap-window -t -1
bind-key . swap-window -t +1

# Rotate panes
bind-key -n M-r rotate-window

# Cycle layouts forward
bind-key -n M-n next-layout

# kill session
bind X kill-session

# Custom keybinding to swap the top and bottom panes
#bind m swap-pane -D

# reload config
bind r source-file ~/.config/tmux/tmux.conf

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Enter copy mode with cursor at beginning of line
bind [ copy-mode \; send-keys -X start-of-line

# switch panes using ctrl + hjkl
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# # switch panes using alt + hjkl
# bind -n M-h select-pane -L
# bind -n M-l select-pane -R
# bind -n M-k select-pane -U
# bind -n M-j select-pane -D

# Resize pane using hjkl
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Enable mouse control
set -g mouse on

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

# reset window index
set -g renumber-windows on

# Blinking bar cursor
set -g cursor-style blinking-bar

# lazyvim
set-option -sg escape-time 10
set-option -g focus-events on
set -g extended-keys on
# set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ',xterm-256color:Tc'

# Message style.
set -g message-style "fg=white,bg=#0D101B"
set -g message-command-style "fg=white,bg=#0D101B"

# Pane style.
set -g pane-border-style "fg=#0C0C0C"
set -g pane-active-border-style "fg=white"

# Status style.
set -g status-interval 5
set -g status-style "fg=white,bg=#0D101B"
set -g status-left "#[fg=blue,bg=#0D101B]#[fg=#0C0C0C,bg=blue]#S#[fg=blue,bg=#0D101B]  "
set -g status-right-length 100
set -g status-right "#[fg=#d7e3fc,bg=#0D101B]#[fg=#0C0C0C,bg=#d7e3fc]󰋔 #(kubectl get pods --all-namespaces --no-headers | grep -vE 'Running|Completed' | wc -l )#[fg=#d7e3fc,bg=#0D101B] #[fg=#e3d5ca,bg=#0D101B]#[fg=#0C0C0C,bg=#e3d5ca] #(free -h | awk '/Mem:/ {print $3 \"/\" $2}')#[fg=#e3d5ca,bg=#0D101B] #[fg=#9DC7C8,bg=#0D101B]#[fg=#0C0C0C,bg=#9DC7C8] #{cpu_percentage}#[fg=#9DC7C8,bg=#0D101B] #[fg=#8d99ae,bg=#0D101B]#[fg=#0C0C0C,bg=#8d99ae] %H:%M#[fg=#8d99ae,bg=#0D101B] "
set -g status-left-length 100
set -g status-justify left
set-option -g status-position top

# Window style.
set -g window-status-style "fg=colour8,bg=#0C0C0C"
set -g window-status-format "#[fg=#444444,bg=#0D101B] #[fg=white,bg=#0D101B]#W"
set -g window-status-separator "  "
set -g window-status-current-format "#[fg=cyan,bg=#0D101B] #[fg=gray,bg=#0D101B]#W"

# scripts
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer.sh"

# tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm'

