exec-once = gammastep -m wayland -o eDP-1 -O 5800

# App autostart on specific workspaces
exec-once = [workspace 1 silent] uwsm-app -- google-chrome-stable
exec-once = [workspace 6 silent] uwsm-app -- teams-for-linux --disable-features=SpellingService
exec-once = [workspace 7 silent] omarchy-launch-webapp "https://outlook.live.com"
exec-once = [workspace 3 silent] uwsm-app -- firefox

