# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- swayosd-server

# App autostart on specific workspaces
exec-once = [workspace 1 silent] uwsm-app -- firefox
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec
exec-once = [workspace 4 silent] uwsm-app -- spotify
