# App autostart on specific workspaces
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec
exec-once = [workspace 5 silent] uwsm-app -- spotify
exec-once = [workspace 9 silent] omarchy-launch-webapp "https://chatgpt.com"

source = ~/.config/hypr/autostart-local.conf
