#🐢
scan_timeout = 30
command_timeout = 500

[nodejs]
disabled = true
[kubernetes]
format = 'on [🐳 $context \($namespace\)](white) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "white", symbol = "💔 " },
]

[username]
style_user = 'purple'
style_root = 'red'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false
